### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gpcr** [STAR-Fusion/STAR-Fusion#1]
Intervals must have positive width at STAR-Fusion/STAR-Fusion line 682, <$__ANONIO__> line 84548.

when using with Ensembl Homo_sapiens.GRCh37.75.gtf

**Comment by brianjohnhaas** [comment]
Code is now updated. I'll put out a new pre-release shortly.  Thanks!

**Comment by cruckert** [comment]
Is it possible this bug reoccured in the latest version?

-parsing Homo_sapiens.GRCh37.75.gtf
-building interval tree for fast searching of gene overlaps
-mapping junction reads to genes
Intervals must have positive width at /opt/STAR_2.5.1b/STAR-Fusion/STAR-Fusion line 682, <__ANONIO__> line 8645.

**Comment by brianjohnhaas** [comment]
Hi

I thought this was already fixed.  Are you using the provided genome files or using your own?

Thx

-Brian
(by iPhone)

**Comment by cruckert** [comment]
I'm using my own .gtf downloaded from Ensembl, as the reads were aligned against a reference .fasta without "chr" in the chromosome names and I get empty result files using the genome files provided by you.

**Comment by cruckert** [comment]
After realigning to a reference with chr in chromosome names and using your gencode.v19.annotation.gtf.exons.gz file the error persists:

parsing gunzip -c /opt/STAR_2.5.1b/STAR-Fusion/resources/gencode.v19.annotation.gtf.exons.gz | 
-building interval tree for fast searching of gene overlaps
-mapping junction reads to genes
Intervals must have positive width at /opt/STAR_2.5.1b/STAR-Fusion/STAR-Fusion line 682, <__ANONIO__> line 48006.

Does the second line value (48006) refer to Chimeric.out.sam or Chimeric.out.junction?

**Comment by brianjohnhaas** [comment]
Are you using the latest version of the software?  There is no line 682 in
the latest code.

https://github.com/STAR-Fusion/STAR-Fusion/blob/master/STAR-Fusion

If you're using code that came with STAR pulled as a recursive submodule,
it's probably very outdated.  I'll chat with Alex Dobin about this.

Get the latest code here:
https://github.com/STAR-Fusion/STAR-Fusion/releases

You shouldn't encounter that problem w/ this code.

best,

~b

On Wed, Mar 2, 2016 at 8:42 AM, cruckert <notifications@github.com> wrote:

> After realigning to a reference with chr in chromosome names and using
> your gencode.v19.annotation.gtf.exons.gz file the error persists:
>
> parsing gunzip -c
> /opt/STAR_2.5.1b/STAR-Fusion/resources/gencode.v19.annotation.gtf.exons.gz
> |
> -building interval tree for fast searching of gene overlaps
> -mapping junction reads to genes
> Intervals must have positive width at
> /opt/STAR_2.5.1b/STAR-Fusion/STAR-Fusion line 682, <*ANONIO*> line 48006.
>
> Does the second line value (48006) refer to Chimeric.out.sam or
> Chimeric.out.junction?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/1#issuecomment-191242388>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by cruckert** [comment]
Thanks a lot! The current version resolved my issues.

Regards,
Christian

**Comment by brianjohnhaas** [comment]
Excellent!  Thanks for the update,

~brian


On Thu, Mar 3, 2016 at 10:57 AM, cruckert <notifications@github.com> wrote:

> Thanks a lot! The current version resolved my issues.
>
> Regards,
> Christian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STAR-Fusion/STAR-Fusion/issues/1#issuecomment-191825940>
> .
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>
